### PR TITLE
Add AXFR integration tests for kubernetes plugin

### PR DESCRIPTION
**Pull request by davidmccormick**
Whilst testing a CoreDNS upgrade, we discovered that Zone Transfers / AXFR requests were failing to produce the expected results.  This occurred around the introduction of the transfer plugin.  We noticed that AXFR is not covered by the existing ci integration tests.

Before we write integration tests to support https://github.com/coredns/kubernetai/pull/66 which adds AXFR back into the kubernetai plugin we want some tests that prove that the embedded kubernetes plugin is working as anticipated.

Details

1. Add two AXFR tests - one with services and one which tests pod endpoints.
2. Regex matches any IPV4 address because these can change between test environments and different runs.
3. Changing the pause container from `gcr.io/google_containers/pause-amd64:3.0` to `k8s.gcr.io/pause:3.9` helps developers run the tests on ARM hardware (e.g. modern Macs).
4. Added some custom code paths for testing AXFR queries and parsing AXFR responses because they differ from the existing tests.
5. AXFR tests are performed in test-4 and test-5 namespaces so that they do interfere with existing test suites.
6. Checking for a nil test result rather than panicking gives us the opportunity of displaying the logs.

### CODE REVIEW

**Comment by davidmccormick** [comment]
Looks like the build of the metadata plugin is failing...

```
github.com/coredns/metadata_edns0
# github.com/coredns/metadata_edns0
link: golang.org/x/net/internal/socket: invalid reference to syscall.recvmsg
make: *** [Makefile:32: build] Error 1
[+] Building 0.3s (13/13) FINISHED                               docker:default
 => [internal] load build definition from Dockerfile                       0.0s
```

**Comment by davidmccormick** [comment]
This PR fixes the failed build https://github.com/coredns/metadata_edns0/pull/22

**Comment by davidmccormick** [comment]
The Kubernetes plugin already supports the transfer plugin and post-merge these additional AXFR tests will pass.

**Comment by chrisohaver** [comment]
Thanks for adding this!

**Pull request merged**
