### PR TITLE
WIP: Compile CoreDNS with -race

### LINKED ISSUE #70: CoreDNS is compiled without -race
https://github.com/coredns/ci/blob/master/Makefile

this doesn't enabled `-race` for the build; which is a good thing to have in this test.

### PR DESCRIPTION
**Pull request by chrisohaver**
fixes #70

### CODE REVIEW

**Comment by fturib** [comment]
that works ... but why sneaking the "-race" in a variable that has nothing to do with ?
it is complicated to add another variable ?

**Comment by chrisohaver** [comment]
I didnt want to have to modify the Makefile in coredns/coredns - but looks like I have to do that anyways....

**Comment by chrisohaver** [comment]
When this is run inside a container, the container immediately fails with a "no such file or directory" error.  Most people encounter this error when docker fails to execute the entry point... e.g. if the binary doesn't exist, or isn't executable...  but the compile passes OK, and then I build locally, the binary produced is executable (as always has been).

**Comment by chrisohaver** [comment]
Perhaps you need go to be installed to run a binary that is compiled with -race?

**Comment by chrisohaver** [comment]
@miekg, any ideas why this is occurring?

When the CI builds the docker image with coredns compiled with `-race` flag, the docker images immediately abort with:
```
Standard_init_linux.go:187: exec user process caused “no such file or directory”
```

This is the kind of error you see when the entrypoint is not executable, or missing.  But I verified that the coredns binary produced by the build is existing, executable, and functional, by hopping on to drone and looking in the test working directory while the test was running.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/ci] WIP: Compile CoreD..." ]
>@miekg, any ideas why this is occurring?
>
>When the CI builds the docker image with coredns compiled with `-race` flag, the docker images immediately abort with:
>```
>Standard_init_linux.go:187: exec user process caused “no such file or directory”
>```

you enabled cgo, there is no libc in the docker image so *boom*

**Comment by chrisohaver** [comment]
Ah thanks. I thought it was all statically linked, but I guess no when it uses c libs.

On Oct 9, 2018, at 4:28 PM, Miek Gieben <notifications@github.com<mailto:notifications@github.com>> wrote:

[ Quoting <notifications@github.com<mailto:notifications@github.com>> in "Re: [coredns/ci] WIP: Compile CoreD..." ]
>@miekg, any ideas why this is occurring?
>
>When the CI builds the docker image with coredns compiled with `-race` flag, the docker images immediately abort with:
>```
>Standard_init_linux.go:187: exec user process caused “no such file or directory”
>```

you enabled cgo, there is no libc in the docker image so *boom*

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/ci] WIP: Compile CoreD..." ]
>Ah thanks. I thought it was all statically linked, but I guess no when it uses c libs.

We shoulnd't need cgo, so I wonder why -race wants it. Keep be a dep we pull in.

**Comment by chrisohaver** [comment]
> We shouldn't need cgo, so I wonder why -race wants it. 

Detecting races perhaps requires very fast memory access analysis - ergo written in C?
Regardless, `-race` requires it, so if we want to employ race detection in the k8s integration tests, we will need to build a special docker image for the tests, which is annoying.

**Pull request closed without merging**
