### PR TITLE
Update Caddy's import path

### PR DESCRIPTION
**Pull request by yongtang**
See https://github.com/coredns/coredns/issues/2959

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by yongtang** [comment]
There are some circular dependency so will go ahead and merge this PR first, so that PR https://github.com/coredns/coredns/pull/2961 could be updated and merged.

**Comment by rajansandeep** [comment]
@yongtang the CI tests failed. Is this expected until all the dependent PRs are merged?

**Comment by yongtang** [comment]
@rajansandeep Yes see coredns/coredns#2961, once it is merged ci should pass.

**Comment by yongtang** [comment]
coredns/coredns#2961 has been merged. All tests passes now.

**Comment by miekg** [comment]
cc @johnbelamaric this is probably relevant for "Learning CoreDNS"

**Comment by johnbelamaric** [comment]
Thanks, I'll take a note of it!

**Pull request merged**
